dist: bionic

os: linux

language: shell

services:
  - docker

env:
  global:
    - DOCKER_ORG_NAME=tidair
    - DOCKER_SERVER_REPO=pysmurf-server-base
    - DOCKER_CLIENT_REPO=pysmurf-client

# Install dependencies
addons:
  apt:
    packages:
      - flake8

stages:
  - checks
  - tests
  - name: deploy_server_docker
    if: tag IS present
  - name: deploy_client_docker
    if: tag IS present

jobs:
  include:
    # Check stages
    ## Flake8 checks
    - stage: checks
      name: "Flake8 Checks"
      script:
        # Run Flake8
        - flake8 --count python/

    # Test stages
    ## Server tests
    - stage: tests
      name: "Server Tests"
      install:
        # Build the server docker
        - cd docker/server/
        - docker build --build-arg branch=$TRAVIS_BRANCH -t server_docker .
        - cd -

      before_script:
        # Start the server container in the background
        - |
          docker run -dti --rm --name server \
          --entrypoint bash \
          server_docker

      script:
        # Try to import the smurf module in the server container
        - |
          docker exec server \
          /bin/bash -c "python3 -c 'import rogue; import smurf;'"

        # Try to import the pysmurf's SmurfProcessor module in the server container
        - |
          docker exec server \
          /bin/bash -c "python3 -c 'import pysmurf.core.devices; \
          s = pysmurf.core.devices.SmurfProcessor(name=\"\", description=\"\")'"

    ## Client tests
    - stage: tests
      name: "Client Tests"
      install:
        # Build the client docker
        - cd docker/client/
        - docker build --build-arg branch=$TRAVIS_BRANCH -t client_docker .
        - cd -

      before_script:
        # Start the client container in the background
        - |
          docker run -dti --rm --name client \
          --entrypoint bash \
          client_docker

        ## TO DO ##
        # Fix this test in travis. It is failing when trying to import matplotlib
        # with: assertion 'GDK_IS_DISPLAY (display)' failed
        ## TO DO ##
        # Try to import the pysmurf.client module in the client container
        # - |
        #   docker exec client \
        #   /bin/bash -c "PYTHONPATH=/root/pysmurf/lib:/root/pysmurf/python:${PYTHONPATH} \
        #   python3 -c 'import pysmurf.client'"

    # Deployment stage for the server docker
    - stage: deploy_server_docker
      name: "Deploy Server Docker Image"
      before_script:
        # Use the git tag to tag tag docker image
        - export DOCKER_TAG=`git describe --tags --always`
        # Login to docker
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ORG_NAME}" --password-stdin;

      script:
        # Build the docker image
        - cd docker/server/
        - docker build --build-arg branch=$TRAVIS_BRANCH -t ${DOCKER_ORG_NAME}/${DOCKER_SERVER_REPO} .

      after_success:
        # Upload docker image (as tagged and latest version)
        - docker push ${DOCKER_ORG_NAME}/${DOCKER_SERVER_REPO};
        - docker tag ${DOCKER_ORG_NAME}/${DOCKER_SERVER_REPO} ${DOCKER_ORG_NAME}/${DOCKER_SERVER_REPO}:${DOCKER_TAG};
        - docker push ${DOCKER_ORG_NAME}/${DOCKER_SERVER_REPO}:${DOCKER_TAG};

    # Deployment stage for the client docker
    - stage: deploy_client_docker
      name: "Deploy Client Docker Image"
      before_script:
        # Use the git tag to tag tag docker image
        - export DOCKER_TAG=`git describe --tags --always`
        # Login to docker
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ORG_NAME}" --password-stdin;

      script:
        # Build the docker image
        - cd docker/client/
        - docker build --build-arg branch=$TRAVIS_BRANCH -t ${DOCKER_ORG_NAME}/${DOCKER_CLIENT_REPO} .

      after_success:
        # Upload docker image (as tagged and latest version)
        - docker push ${DOCKER_ORG_NAME}/${DOCKER_CLIENT_REPO};
        - docker tag ${DOCKER_ORG_NAME}/${DOCKER_CLIENT_REPO} ${DOCKER_ORG_NAME}/${DOCKER_CLIENT_REPO}:${DOCKER_TAG};
        - docker push ${DOCKER_ORG_NAME}/${DOCKER_CLIENT_REPO}:${DOCKER_TAG};
